### ISSUE TITLE
Change color of JTAG pins to match actual cable colors

### ISSUE THREAD

**Issue by deragent** [lupusorina/cern_winter_school#1]
In  isotdaq2019_soc_lab/doc/Students_Guide_ISOTDAQ_SoC_FPGA_Lab_2019-2.pdf  under point 3.2.1 (page 10), the pinout for the JTAG connector is shown.

The colors used in this figure are similar to the actual colors of the JTAG cables but do not correspond 100%.

For the future we should change this, in order to not confuse the students.

**Comment by lupusorina** [comment]
Good point, I fixed it.

**Comment by Abdull** [comment]
is there an official standard to JTAG data line colors?
